stages:
    - build
    - test
    - deploy

build job:
    stage: build
    tags:
        - windows
    script:
        - msbuild "Freeform Light.sln" /property:platform=x64 /property:target=Debug
        - msbuild "Freeform Light.sln" /property:platform=x64 /property:target=Release
        - msbuild "Freeform Light.sln" /property:platform=x64 /property:target=Profile

test job:
    script:
        - echo "test coming soon"
        
deploy job:
    script:
        - echo "deploy coming soon"