variables:
  MSBUILD: "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe"

stages:
    - build
    - test
    - deploy
    - release

build_job:
    stage: build    
    tags:
        - ehei
    script:
        - git submodule init
        - git submodule update
        - echo $MSBUILD
        - $MSBUILD "dot.sln" /property:platform=x86 /property:target=Debug
        - $MSBUILD "dot.sln" /property:platform=x86 /property:target=Release
        - $MSBUILD "dot.sln" /property:platform=x86 /property:target=Profile

test_job:
    stage: test
    script:
        - echo "test coming soon"
    tags:
        - ehei
        
deploy_job:
    stage: deploy
    script:
        - echo "deploy coming soon"
    tags:
        - ehei

release_job:
    stage: 'release'
    only:
        - master
        - 'publish'
    script:
        - echo "running release_job"
    release: 
        name: 'Release $CI_COMMIT_SHA'
        description: 'Created using the release-cli about foo'
        tag_name: 'release-$CI_COMMIT_SHA'
        ref: '$CI_COMMIT_SHA'
