stages:
    - build
    - test
    - deploy

build job:
    stage: build
    
    tags:
        - ehei
    script:
        - $loc = ${Env:ProgramFiles(x86)} + '\Microsoft Visual Studio 14.0\Common7\Tools'
        # https://gist.github.com/sqeezy/11863647662b42e3b66b70331156c490
        - pushd $loc
        - cmd /c "vsvars32.bat&set" |
            foreach {
              if ($_ -match "=") {
                $v = $_.split("="); set-item -force -path "ENV:\$($v[0])"  -value "$($v[1])"
              }
            }
        - popd
        - git submodule init
        - git submodule update
        - chcp 850
        - msbuild "dot.sln" /property:platform=x86 /property:target=Debug
        - msbuild "dot.sln" /property:platform=x86 /property:target=Release
        - msbuild "dot.sln" /property:platform=x86 /property:target=Profile

test job:
    script:
        - echo "test coming soon"
    tags:
        - ehei
        
deploy job:
    script:
        - echo "deploy coming soon"
    tags:
        - ehei
