stages:
    - build
    - test
    - deploy

build job:
    stage: build
    tags:
        - windows
    script:
        - echo "hi"


test job:
    script:
        - echo "test coming soon"
        
deploy job:
    script:
        - echo "deploy coming soon"