variables:
  MSBUILD: ${Env:ProgramFiles(x86)} + '\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin'

stages:
    - build
    - test
    - deploy

build_job:
    stage: build    
    tags:
        - ehei
    script:
        - git submodule init
        - git submodule update
        - chcp 850
        - $MSBUILD "dot.sln" /property:platform=x86 /property:target=Debug
        - $MSBUILD "dot.sln" /property:platform=x86 /property:target=Release
        - $MSBUILD "dot.sln" /property:platform=x86 /property:target=Profile

test job:
    script:
        - echo "test coming soon"
    tags:
        - ehei
        
deploy job:
    script:
        - echo "deploy coming soon"
    tags:
        - ehei
